<?php

$sql = "CREATE TABLE users (id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(20) NOT NULL,lastname VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL,
gender TINYINT, status TINYINT)";

return $sql;
